// Client-safe constants for the Gemini integration
// These can be imported by both client and server components

export const SUPPORTED_AUDIO_TYPES = [
    "audio/mpeg",
    "audio/mp3",
    "audio/mp4",
    "audio/m4a",
    "audio/x-m4a",
    "audio/wav",
    "audio/webm",
    "audio/ogg",
    "audio/aac",
    "audio/x-caf",
    "audio/caf",
];

// Source languages/dialects the user can specify
export const SOURCE_LANGUAGES = [
    { code: "auto", name: "Auto-detect" },
    // Arabic dialects
    { code: "ar-YE", name: "Arabic (Yemeni)" },
    { code: "ar-YE-sanaa", name: "Arabic (Yemeni - Sana'ani)" },
    { code: "ar-YE-hadrami", name: "Arabic (Yemeni - Hadhrami)" },
    { code: "ar-YE-taizzi", name: "Arabic (Yemeni - Ta'izzi-Adeni)" },
    { code: "ar-SA", name: "Arabic (Saudi)" },
    { code: "ar-AE", name: "Arabic (Emirati/Gulf)" },
    { code: "ar-KW", name: "Arabic (Kuwaiti)" },
    { code: "ar-QA", name: "Arabic (Qatari)" },
    { code: "ar-BH", name: "Arabic (Bahraini)" },
    { code: "ar-OM", name: "Arabic (Omani)" },
    { code: "ar-IQ", name: "Arabic (Iraqi)" },
    { code: "ar-SY", name: "Arabic (Syrian)" },
    { code: "ar-LB", name: "Arabic (Lebanese)" },
    { code: "ar-JO", name: "Arabic (Jordanian)" },
    { code: "ar-PS", name: "Arabic (Palestinian)" },
    { code: "ar-EG", name: "Arabic (Egyptian)" },
    { code: "ar-SD", name: "Arabic (Sudanese)" },
    { code: "ar-LY", name: "Arabic (Libyan)" },
    { code: "ar-TN", name: "Arabic (Tunisian)" },
    { code: "ar-DZ", name: "Arabic (Algerian)" },
    { code: "ar-MA", name: "Arabic (Moroccan)" },
    { code: "ar", name: "Arabic (Modern Standard)" },
    // Other languages
    { code: "en-US", name: "English (American)" },
    { code: "en-GB", name: "English (British)" },
    { code: "en-AU", name: "English (Australian)" },
    { code: "es-ES", name: "Spanish (Spain)" },
    { code: "es-MX", name: "Spanish (Mexican)" },
    { code: "es-AR", name: "Spanish (Argentine)" },
    { code: "fr-FR", name: "French (France)" },
    { code: "fr-CA", name: "French (Canadian)" },
    { code: "de-DE", name: "German" },
    { code: "it-IT", name: "Italian" },
    { code: "pt-BR", name: "Portuguese (Brazilian)" },
    { code: "pt-PT", name: "Portuguese (European)" },
    { code: "zh-CN", name: "Chinese (Mandarin)" },
    { code: "zh-TW", name: "Chinese (Taiwanese)" },
    { code: "zh-HK", name: "Chinese (Cantonese)" },
    { code: "ja-JP", name: "Japanese" },
    { code: "ko-KR", name: "Korean" },
    { code: "hi-IN", name: "Hindi" },
    { code: "ur-PK", name: "Urdu" },
    { code: "ru-RU", name: "Russian" },
    { code: "tr-TR", name: "Turkish" },
    { code: "vi-VN", name: "Vietnamese" },
    { code: "th-TH", name: "Thai" },
    { code: "id-ID", name: "Indonesian" },
    { code: "ms-MY", name: "Malay" },
    { code: "tl-PH", name: "Tagalog" },
    { code: "sw", name: "Swahili" },
    { code: "am", name: "Amharic" },
    { code: "so", name: "Somali" },
];

export const TARGET_LANGUAGES = [
    { code: "en", name: "English" },
    { code: "es", name: "Spanish" },
    { code: "fr", name: "French" },
    { code: "de", name: "German" },
    { code: "it", name: "Italian" },
    { code: "pt", name: "Portuguese" },
    { code: "zh", name: "Chinese (Mandarin)" },
    { code: "ja", name: "Japanese" },
    { code: "ko", name: "Korean" },
    { code: "ar", name: "Arabic" },
    { code: "hi", name: "Hindi" },
    { code: "ru", name: "Russian" },
    { code: "tr", name: "Turkish" },
    { code: "vi", name: "Vietnamese" },
    { code: "th", name: "Thai" },
    { code: "nl", name: "Dutch" },
    { code: "pl", name: "Polish" },
    { code: "sv", name: "Swedish" },
    { code: "id", name: "Indonesian" },
    { code: "he", name: "Hebrew" },
    { code: "ur", name: "Urdu" },
    { code: "sw", name: "Swahili" },
    { code: "tl", name: "Tagalog" },
];
