"use client";

import { useState, useRef, useEffect } from "react";

interface TranslationResultProps {
    dialect: string;
    transcription: string;
    transliteration?: string;
    translation: string;
    targetLanguage: string;
    audioUrl?: string;
}

export function TranslationResult({
    dialect,
    transcription,
    transliteration,
    translation,
    targetLanguage,
    audioUrl,
}: TranslationResultProps) {
    const [showCopyFeedback, setShowCopyFeedback] = useState(false);
    const [isPlaying, setIsPlaying] = useState(false);
    const audioRef = useRef<HTMLAudioElement>(null);

    useEffect(() => {
        const audio = audioRef.current;
        if (!audio) return;

        const handleEnded = () => setIsPlaying(false);
        const handlePause = () => setIsPlaying(false);
        const handlePlay = () => setIsPlaying(true);

        audio.addEventListener("ended", handleEnded);
        audio.addEventListener("pause", handlePause);
        audio.addEventListener("play", handlePlay);

        return () => {
            audio.removeEventListener("ended", handleEnded);
            audio.removeEventListener("pause", handlePause);
            audio.removeEventListener("play", handlePlay);
        };
    }, []);

    const togglePlayback = () => {
        const audio = audioRef.current;
        if (!audio) return;

        if (isPlaying) {
            audio.pause();
        } else {
            audio.play();
        }
    };

    const copyToClipboard = async (text: string) => {
        try {
            await navigator.clipboard.writeText(text);
            setShowCopyFeedback(true);
            setTimeout(() => setShowCopyFeedback(false), 2000);
        } catch {
            const textArea = document.createElement("textarea");
            textArea.value = text;
            document.body.appendChild(textArea);
            textArea.select();
            document.execCommand("copy");
            document.body.removeChild(textArea);
            setShowCopyFeedback(true);
            setTimeout(() => setShowCopyFeedback(false), 2000);
        }
    };

    const downloadResults = () => {
        const content = `VOICE NOTE TRANSLATION
======================

Detected Language/Dialect: ${dialect}

--- ORIGINAL TRANSCRIPTION ---
${transcription}
${transliteration ? `\n--- TRANSLITERATION ---\n${transliteration}` : ""}

--- TRANSLATION (${targetLanguage}) ---
${translation}

---
Generated by Translate Voice Notes
`;

        const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
        const url = URL.createObjectURL(blob);
        const link = document.createElement("a");
        link.href = url;
        link.download = `translation-${new Date().toISOString().split("T")[0]}.txt`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    };

    const copyAll = () => {
        const content = `Detected: ${dialect}\n\nOriginal:\n${transcription}${transliteration ? `\n\nTransliteration:\n${transliteration}` : ""}\n\nTranslation:\n${translation}`;
        copyToClipboard(content);
    };

    return (
        <div className="results">
            {/* Audio Player */}
            {audioUrl && (
                <div className="results__audio">
                    <audio ref={audioRef} src={audioUrl} preload="metadata" />
                    <button
                        type="button"
                        className="results__audio-btn"
                        onClick={togglePlayback}
                        aria-label={isPlaying ? "Pause audio" : "Play audio"}
                    >
                        {isPlaying ? (
                            <svg viewBox="0 0 24 24" fill="currentColor">
                                <rect x="6" y="4" width="4" height="16" rx="1" />
                                <rect x="14" y="4" width="4" height="16" rx="1" />
                            </svg>
                        ) : (
                            <svg viewBox="0 0 24 24" fill="currentColor">
                                <path d="M8 5v14l11-7z" />
                            </svg>
                        )}
                    </button>
                    <span className="results__audio-label">Play Voice Note</span>
                </div>
            )}

            <div className="results__header">
                <div className="results__dialect">
                    <svg className="results__dialect-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                        <circle cx="12" cy="12" r="10" />
                        <path d="M2 12h20M12 2a15.3 15.3 0 014 10 15.3 15.3 0 01-4 10 15.3 15.3 0 01-4-10 15.3 15.3 0 014-10z" />
                    </svg>
                    {dialect}
                </div>
                <div className="results__actions">
                    <button
                        type="button"
                        className="btn btn--secondary btn--small"
                        onClick={copyAll}
                        title="Copy all"
                    >
                        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                            <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
                            <path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1" />
                        </svg>
                        Copy
                    </button>
                    <button
                        type="button"
                        className="btn btn--secondary btn--small"
                        onClick={downloadResults}
                        title="Download as text file"
                    >
                        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                            <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4M7 10l5 5 5-5M12 15V3" strokeLinecap="round" strokeLinejoin="round" />
                        </svg>
                        Download
                    </button>
                </div>
            </div>

            <div className="results__section">
                <div className="results__section-label">Original Transcription</div>
                <div className="results__section-text">{transcription}</div>
            </div>

            {transliteration && (
                <div className="results__section">
                    <div className="results__section-label">Transliteration (Romanized)</div>
                    <div className="results__section-text results__section-text--transliteration">{transliteration}</div>
                </div>
            )}

            <div className="results__section">
                <div className="results__section-label">Translation</div>
                <div className="results__section-text">{translation}</div>
            </div>

            {showCopyFeedback && (
                <div className="copy-feedback">Copied to clipboard!</div>
            )}
        </div>
    );
}
